from typing import Protocol

from .models import Task


class TaskRepository(Protocol):
    def list(self) -> list[Task]: ...

    def get(self, task_id: int) -> Task | None: ...

    def create(self, title: str, done: bool = False) -> Task: ...

    def update(self, task_id: int, title: str, done: bool) -> Task | None: ...

    def delete(self, task_id: int) -> bool: ...

    def ping(self) -> bool: ...

    def close(self) -> None: ...
